apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: translation-wp-build
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
        - ref: translation-workplace-api-build
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secretToken
            eventTypes: 
              - push
      template: 
        name: translation-workplace-api-build
