apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize-image
spec:
  params:
    - name: image-with-tag
      description: contains image=image:tag in that format
  workspaces:
    - name: source
      description: contains the cloned git repo
  steps:
    - name: kustomize-build
      image: image-registry.openshift-image-registry.svc:5000/shuichi-saitoh-tekton/kustomize:docker
      script: |
        #!/bin/sh
        cd ./source/k8s
        kustomize edit set image $(params.image-with-tag)

        kustomize build > manifests.yaml
        if [ -f manifests.yaml ]; then
          echo "manifests.yaml successfully generated"
          echo "contents of manifests is:"
          cat manifests.yaml
        else
          echo "ERROR: manifests.yaml not generated"
          exit 1
        fi