apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tw-api-build-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: translation-workplace-api-build
  params:
    - name: app-namespace
      value: shuichi-saitoh-tekton
    - name: app-name
      value: translation-workplace-api
  workspaces:
    - name: defaultws
      persistentVolumeClaim:
        claimName: tekton-ws-pvc
      # volumeClaimTemplate:
      #   spec:
      #     accessModes:
      #       - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 1Gi
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: 10.5.197.35
      