apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: translation-workplace-api-build
spec:
  workspaces:
    - name: defaultws
  params:
    - name: IMAGE
      type: string
      description: image to be built from the code
      default: quay.io/shu1saitohibm/translation-workplace-api
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/tekton-expressapp-shuichi-saitoh.git
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: defaultws
    - name: build-and-push-container
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: "$(params.IMAGE):$(tasks.git-clone.results.commit)"
      workspaces:
        - name: source
          workspace: defaultws
      runAfter:
        - git-clone
    - name: kustomize
      taskRef: 
         name: kustomize-image
         kind: Task
      params:
        - name: image-with-tag
          value: $(params.IMAGE):latest
      runAfter:
        - build-and-push-container
      workspaces:
        - name: source
          workspace: defaultws
