apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: translation-workplace-api-build
spec:
  workspaces:
    - name: defaultws
  params:
    - name: IMAGE
      type: string
      description: image to be built from the code
      default: quay.io/shu1saitohibm/translation-workplace-api
    - name: app-namespace
      description: namespace that deployment will be tested in
    - name: app-name
      description: the name of the app
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/tekton-expressapp-shuichi-saitoh.git
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: defaultws
    - name: build-and-push-container
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: "$(params.IMAGE):$(tasks.git-clone.results.commit)"
      workspaces:
        - name: source
          workspace: defaultws
      runAfter:
        - git-clone
    - name: run-test
      taskRef:
        name: run-container
        kind: Task
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(tasks.git-clone.results.commit)"
        - name: COMMAND
          value: "npm"
        - name: ARGS
          value: 
            - "test"
        - name: WORKDIR
          value: "/app"
      runAfter:
        - build-and-push-container
    - name: kustomize
      taskRef: 
         name: kustomize-image
         kind: Task
      params:
        - name: image-with-tag
          value: "$(params.IMAGE):$(tasks.git-clone.results.commit)"
      runAfter:
        - build-and-push-container
        #- git-clone
      workspaces:
        - name: source
          workspace: defaultws
    - name: deploy
      taskRef:
         name: test-deploy
         kind: Task
      params:
        - name: app-namespace
          value: $(params.app-namespace)
        - name: app-name
          value: $(params.app-name)
      workspaces:
        - name: source
          workspace: defaultws
      runAfter:
        - kustomize
        - run-test

        