apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-container
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: build-tool
spec:
  description: >-
    This task can be used to run npm goals on a project.
  params:
    - name: IMAGE
      type: string
      description: image you want to use.
    - name: COMMAND
      type: string
      description: Command to run.
    - name: ARGS
      type: array
      default: []
      description: Arguments to pass to the command.
    - name: WORKDIR
      type: string
      description: Working directoy
  steps:
    - name: run-container
      image: $(params.IMAGE)
      command:
        - $(params.COMMAND)
      args:
        - $(params.ARGS)
      workingDir: $(params.WORKDIR)
      env:
        - name: CI
          value: "true"